version: '3.9'

services:
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
  user-service:
    image: user-service
    build:
      context: ./user_service/
      dockerfile: Dockerfile
    init: true
    volumes:
      - ./user_service/:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
volumes:
  postgres_data: