global:
  scrape_interval: 3s

scrape_configs:
  - job_name: "users-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["user-service:8000"]
  - job_name: "training-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["training-service:8000"]