# Generated by Django 5.1.6 on 2025-03-19 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='exercise',
        ),
        migrations.AddField(
            model_name='exercise',
            name='training_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='trainings.training'),
            preserve_default=False,
        ),
    ]
