# Generated by Django 5.1.6 on 2025-03-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_remove_training_exercise_exercise_training_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
