# Generated by Django 5.1.6 on 2025-02-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_activation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='activation_token',
        ),
    ]
