# Generated by Django 5.1.6 on 2025-03-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_passwordreset_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
